spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Abcd1234$
    url: jdbc:mysql://192.168.56.88/t1
  jpa:
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    serialization:
       indent-output: true